#!/usr/bin/env Rscript

suppressPackageStartupMessages(require(argparser))
suppressPackageStartupMessages(require(glue))
suppressPackageStartupMessages(require(rmarkdown))


p <- arg_parser(
  description = "Concordance between SNPchip and WGS MatrixTables",
  name = "concordance", hide.opts = TRUE)
p <- add_argument(p,
                  arg = "--snp",
                  help = "Path to SNPchip MatrixTable.")
p <- add_argument(p,
                  arg = "--wgs",
                  help = "Path to WGS MatrixTable.")
p <- add_argument(p,
                  arg = "--html",
                  help = "Path to output HTML report.")
a <- parse_args(p)

stopifnot(grepl("html$", a$html))

cat(paste0("[", as.character(Sys.time()), "]"), "START concordance!\n")

params_list <- list(
  WGS_MT = a$wgs,
  SNP_MT = a$snp
)

cat("params_list:\n")
print(params_list)

rmarkdown::render(
  input = "concordance.Rmd",
  output_file = a$html,
  params = params_list
)

cat(paste0("[", as.character(Sys.time()), "]", " END concordance!\n"))
