default_language_version:
    python: python3.10
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: 'v4.2.0'
  hooks:
  - id: check-yaml
    exclude: '\.*conda/.*'
  - id: check-case-conflict
  - id: check-merge-conflict
  - id: detect-private-key
  - id: debug-statements
  - id: check-added-large-files

- repo: https://github.com/PyCQA/flake8
  rev: '5.0.4'
  hooks:
  - id: flake8
    additional_dependencies: [flake8-bugbear, flake8-quotes]

- repo: local
  hooks:
    - id: pylint
      name: pylint
      entry: pylint
      language: system
      types: [python]

# Static type analysis (as much as it's possible in python using type hints)
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: 'v0.960'
  hooks:
  - id: mypy
